curl -d '{"name":"User1", "message":"history 10"}' -H 'Content-Type: application/json' 
-H 'Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoyLCJleHAiOjE2NjI3MzA0OTd9.48_RuNzKGbLyi-mySLxRyicwxIZ_6Ocs7TT7ZzAo7n4'  http://localhost:3000/message